### PR TITLE
Adds hasOwnProperty guard to extend.

### PR DESCRIPTION
**Pull request by jeremyckahn**
It's generally a good idea to guard against modifying the `prototype` of an Object when iterating through with a `for...in` loop.

### CODE REVIEW

**Comment by jeremyckahn** [comment]
Just noticed that my editor also cleaned up some trailing whitespace. I can isolate the relevant lines, if you prefer.

**Comment by ericelliott** [comment]
Thanks. I caught several other errors while I was checking out this fix. I may need to revert this back though. It wasn't modifying any prototypes, it was copying from the prototype of the mixins. This fix will make it impossible to inherit the methods of a flyweight object, though. I don't think that's what we really want in this case.

**Comment by jeremyckahn** [comment]
Fair enough.  Sorry I didn't catch this, the tests all passed before I made the Pull Request.

**Comment by ericelliott** [comment]
The errors I caught were not yours. If nothing else, your patch is going to improve the tests -- I want to make sure that flyweights will work as mixins! =)

**Comment by ericelliott** [comment]
Finally got around to adding that test and reverting this change that made it impossible to inherit prototype properties.

I'll be tuning up the API a bit, now.

**Pull request merged**
